fakeflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
path('', include('filme.urls', namespace = 'filme')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/urls.py
# Url - View - Template

from django.urls import path, include
from .views import Homefilmes, Homepage, Detalhesfilme

app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),
]

filme/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


LISTA_CATEGORIAS = (
    ("ACAO", "Ação"),
    ("TERROR", "Terror"),
    ("AVENTURA", "Aventura"),
    ("OUTROS", "Outros"),
)

#Criar o filme
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb =models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.titulo


#Criar os episodios

class Episodio(models.Model):
    filme = models.ForeignKey( "Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + " | " + self.titulo

filme/views.py
from django.shortcuts import render
from .models import Filme
from django.views.generic import TemplateView, ListView, DetailView

# Create your views here.

# def homepage(request):
 #    return  render(request, "homepage.html")

class Homepage(TemplateView):
    template_name = "homepage.html"

# Url - View - html

#def homefilmes(request):
#    context = {}
#    lista_filmes = Filme.objects.all()
#    context['lista_filmes'] = lista_filmes
#    return render(request, "homefilmes.html", context)

class Homefilmes(ListView):
    template_name = "homefilmes.html"
    model = Filme
    # object_list -> Lista de itens do modelo


class Detalhesfilme(DetailView):
    template_name = "detalhesfilme.html"
    model = Filme
    # Object -> 1 item do nosso modelo

filme/templates/detalhesfilme.html
{% extends 'base.html' %}

{% block titulo %}
Homefilmes Fakeflix
{% endblock %}

{% block content %}
<div class="py-20">
<h1>Esse é o detalhe do filme {{ object.titulo }}</h1>
    <p>{{ object }}</p>
        <p>{{ object.descricao }}</p>
        <img src="{{ object.thumb.url }}">

    <h2>Episódios</h2>
    {% for episodio in object.episodios.all %}
    <a href="{{ episodio.video }}">
        <p>Episodio {{ forloop.counter }}: {{ episodio.titulo }}</p>
    </a>
    {% endfor %}
</div>
{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}

{% block titulo %}
Homefilmes Fakeflix
{% endblock %}

{% block content %}
<div class="py-20">
<h1>Essa é a nossa HomeFilmes</h1>
    {% for filme in object_list %}
    <hr>
    <a href="{% url 'filme:detalhesfilme' filme.id %}"><p>{{ filme }}</p></a>
    <p>{{ filme.descricao }}</p>
    <img src="{{ filme.thumb.url }}">
    {% endfor %}
</div>
{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Homepage Fakeflix
{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Filmes e séries da Fakeflix, tudo em um só lugar.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Assista onde quiser. Cancele quando quiser.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        <div class="flex flex-grow items-stretch">
                            <input>
                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            <span>
                                Acessar
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="tv_imagem">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Download your shows to watch offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>

    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2021</li>
            <li> Feito com Python (Django)</li>
            <li>Fakeflix</li>
        </ul>
    </footer>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}

        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>

    {% block head %}
    {% endblock %}
</head>
<body   class="bg-black text-gray-100 font-primary">
{% include 'navbar.html' %}
        {%  block content %}

    {% endblock %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</body>
</html>

templates/navbar.html
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
    <a  href="/">
            <img class="w-3/12"  src="{% static 'images/Fakeflix.png' %}">
    </a>
    </div>

    <div  class="w-6/12 flex flex-nowrap justify-end">
    <div class="mr-2">
        <form>
            <input type="text" class="py-1 px-2 rounded-md text-black" placeholder="Pesquisar...">
        </form>
    </div>
                        <div class="mr-2">
                            <a href="#">
<button class="bg-red-600 text-white py-1 px-3 rounded-md">
    Login
</button>
                                </a>
                        </div >
        <div class="mr-2">
            <a href="#">
<button class="bg-red-600 text-white py-1 px-3 rounded-md">
    Editar Perfil
</button>
                </a>
        </div>
    </div>

</nav>